apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: default
spec:
  amiFamily: AL2

  role: KarpenterNodeRole   # IMPORTANT: must exist

  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: test

  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: test

  tags:
    karpenter.sh/discovery: test
