apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: default
spec:
  template:
    spec:
      nodeClassRef:
        name: default

      requirements:
        - key: kubernetes.io/arch
          operator: In
          values: ["amd64"]

        - key: kubernetes.io/os
          operator: In
          values: ["linux"]

        # CHEAP INSTANCES
        - key: node.kubernetes.io/instance-type
          operator: In
          values: ["t3.micro", "t3.small"]

        - key: karpenter.sh/capacity-type
          operator: In
          values: ["on-demand"]

  limits:
    cpu: "10"
    memory: 20Gi

  disruption:
    consolidationPolicy: WhenEmpty
    consolidateAfter: 30s
